version: "3.9"
services:
  web:
    image: amyangxyz111/6tisch-cloud-web
    environment:
      DB_DB: 6tisch
      DB_USER: uu
      DB_PASSWORD: password
    ports:
      - "8000:80"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    # depends_on:
    #   - db
    # networks:
    #   - n
  ds: 
    image: amyangxyz111/6tisch-cloud-ds
    environment:
      DB_DB: 6tisch
      DB_USER: uu
      DB_PASSWORD: password
    ports:
      - "54321:54321"
    # depends_on:
    #   - db
    # networks:
    #   - n

  db:
    image: linuxserver/mariadb  
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
      MYSQL_DATABASE: 6tisch
      MYSQL_USER: uu
      MYSQL_PASSWORD: password
    expose:
      - "3306"
    ports:
      - "3306:3306"
    # networks:
    #   - n

# networks:
#   n: